export const MONGODB_ID = process.env.NEXT_PUBLIC_MONGODB_ID;
export const MONGODB_PASSWORD = process.env.NEXT_PUBLIC_MONGODB_PASSWORD;
export const MONGODB_CLUSTER = process.env.NEXT_PUBLIC_MONGODB_CLUSTER;
